<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use DB;
class SeederPermisos extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
		DB::statement('SET FOREIGN_KEY_CHECKS = 0;'); // Desactivamos la revisión de claves foráneas
      	DB::table('permisos')->truncate();
      	DB::statement('SET FOREIGN_KEY_CHECKS = 1;'); // Activamos la revisión de claves foráneas
		$permisos = [
			[
				"id" => 1,
				"cdg" => 200,
				"nombre" => "crear_usuario",
				"descripcion" => "Creación de Usuarios",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 2,
				"cdg" => 201,
				"nombre" => "crear_rol",
				"descripcion" => "Creación de Rol",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 3,
				"cdg" => 202,
				"nombre" => "editar_usuario",
				"descripcion" => "Editar de Usuarios",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 4,
				"cdg" => 203,
				"nombre" => "editar_rol",
				"descripcion" => "Editar de Rol",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 5,
				"cdg" => 204,
				"nombre" => "eliminar_restaurar_usuario",
				"descripcion" => "Eliminar de Usuario",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 6,
				"cdg" => 205,
				"nombre" => "eliminar_rol",
				"descripcion" => "Eliminar de rol",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 7,
				"cdg" => 206,
				"nombre" => "activar_desactivar_rol",
				"descripcion" => "Activar Desactivar rol",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 8,
				"cdg" => 207,
				"nombre" => "activar_desactivar_usuario",
				"descripcion" => "Activar y desactivar usuarios",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 9,
				"cdg" => 208,
				"nombre" => "ver_detalles_usuarios",
				"descripcion" => "Ver detalles de Usuarios",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 10,
				"cdg" => 209,
				"nombre" => "ver_detalles_rol",
				"descripcion" => "Ver detalles Roles",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 11,
				"cdg" => 210,
				"nombre" => "ver_listado_usuarios",
				"descripcion" => "Ver listado de Usuarios",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 12,
				"cdg" => 211,
				"nombre" => "ver_listados_rol",
				"descripcion" => "Ver listado de Roles",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 13,
				"cdg" => 100,
				"nombre" => "crear_cadena",
				"descripcion" => "Crear Cadenas",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 14,
				"cdg" => 101,
				"nombre" => "editar_cadena",
				"descripcion" => "Editar Cadenas",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 15,
				"cdg" => 102,
				"nombre" => "ver_detalles_cadena",
				"descripcion" => "Ver detalles de cadenas",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 16,
				"cdg" => 103,
				"nombre" => "activar_desactivar_cadena",
				"descripcion" => "Activar Desactivar Cadenas",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 17,
				"cdg" => 104,
				"nombre" => "eliminar_cadena",
				"descripcion" => "Elimar Cadenas",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 18,
				"cdg" => 105,
				"nombre" => "crear_sala",
				"descripcion" => "Crear Sala",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 19,
				"cdg" => 106,
				"nombre" => "editar_sala",
				"descripcion" => "Editar Sala",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 20,
				"cdg" => 107,
				"nombre" => "avtivar_desactivar_sala",
				"descripcion" => "Activar Desactivar Sala",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 21,
				"cdg" => 108,
				"nombre" => "borrar_sala",
				"descripcion" => "Eliminar Sala",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 22,
				"cdg" => 109,
				"nombre" => "crear_seccion",
				"descripcion" => "Crear Sección",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 23,
				"cdg" => 110,
				"nombre" => "editar_seccion",
				"descripcion" => "Editar Sección",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 24,
				"cdg" => 111,
				"nombre" => "estatus_seccion",
				"descripcion" => "Activar Desactivar Sección",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 25,
				"cdg" => 112,
				"nombre" => "borrar_sesion",
				"descripcion" => "Borrar sección",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 26,
				"cdg" => 113,
				"nombre" => "ver_listado_cadenas",
				"descripcion" => "Ver listado de cadenas",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 27,
				"cdg" => 114,
				"nombre" => "ver_listados_salas",
				"descripcion" => "Ver listado de salas ",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 28,
				"cdg" => 115,
				"nombre" => "ver_listados_sesiones",
				"descripcion" => "Ver listado de Secciones",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 29,
				"cdg" => 401,
				"nombre" => "ver_listado_faldones",
				"descripcion" => "Ver listado de faldones",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 30,
				"cdg" => 402,
				"nombre" => "crear_faldones",
				"descripcion" => "Crear faldones",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 31,
				"cdg" => 403,
				"nombre" => "descargar_excel_faldones",
				"descripcion" => "Descargar excel del faldon",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 32,
				"cdg" => 404,
				"nombre" => "editar_faldon",
				"descripcion" => "Editar faldones existentes",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 33,
				"cdg" => 405,
				"nombre" => "descargar_pdf_faldon",
				"descripcion" => "descargar faldon pdf",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 34,
				"cdg" => 406,
				"nombre" => "ver_detalles_faldon",
				"descripcion" => "Ver detalles campaña faldon",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 35,
				"cdg" => 407,
				"nombre" => "eliminar_faldon",
				"descripcion" => "Eliminar Campaña faldon",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 36,
				"cdg" => 300,
				"nombre" => "crear_campana",
				"descripcion" => "Crear las campañas de los proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 3,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 37,
				"cdg" => 301,
				"nombre" => "editar_campana",
				"descripcion" => "Editar las campañas de los proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 3,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 38,
				"cdg" => 302,
				"nombre" => "gestionar_campana",
				"descripcion" => "Gestiona las campañas de los proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 3,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 39,
				"cdg" => 303,
				"nombre" => "implementar_campana",
				"descripcion" => "Implementar las campañas de los proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 3,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 40,
				"cdg" => 304,
				"nombre" => "reportar_campana",
				"descripcion" => "Reportar las campañas de los proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 3,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 41,
				"cdg" => 305,
				"nombre" => "eliminar_campana",
				"descripcion" => "Eliminar las campañas de los proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 3,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 42,
				"cdg" => 306,
				"nombre" => "ver_campana",
				"descripcion" => "Ver las campañas de los proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 3,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 43,
				"cdg" => 307,
				"nombre" => "ver_incidencias",
				"descripcion" => "Ver las incidencias campañas de los proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 3,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 46,
				"cdg" => 500,
				"nombre" => "crear_usuario_proveedor",
				"descripcion" => "Crear los usuarios de los proveedores",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 12:01:15",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 47,
				"cdg" => 501,
				"nombre" => "editar_usuario_proveedor",
				"descripcion" => "Editar los usuarios de los proveedores",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 12:01:15",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 48,
				"cdg" => 502,
				"nombre" => "eliminar_restaurar_usuario_proveedor",
				"descripcion" => "Eliminar los usuarios de los proveedores",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 12:01:15",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 49,
				"cdg" => 503,
				"nombre" => "activarr_usuario_proveedor",
				"descripcion" => "Activar los usuarios de los proveedores",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 12:01:15",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 50,
				"cdg" => 504,
				"nombre" => "desactivar_usuario_proveedor",
				"descripcion" => "Desactivar los usuarios de los proveedores",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 12:01:15",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 51,
				"cdg" => 505,
				"nombre" => "subir_campana_proveedor",
				"descripcion" => "Subir la campanas de los proveedores",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 12:01:15",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 52,
				"cdg" => 506,
				"nombre" => "responder_incidencia",
				"descripcion" => "Responde las incidencias de los proveedores",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 12:01:15",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 53,
				"cdg" => 507,
				"nombre" => "ver_detalles_usuarios_proveedor",
				"descripcion" => "Ver detalles de Usuarios Proveedor",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 54,
				"cdg" => 508,
				"nombre" => "crear_rol_proveedor",
				"descripcion" => "Creación de Rol para proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 2,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 55,
				"cdg" => 509,
				"nombre" => "editar_rol_proveedor",
				"descripcion" => "Editar de Rol Proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 56,
				"cdg" => 510,
				"nombre" => "eliminar_rol_proveedor",
				"descripcion" => "Eliminar de rol Proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 57,
				"cdg" => 511,
				"nombre" => "activar_desactivar_rol_proveedor",
				"descripcion" => "Activa o Desactivar rol Proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 58,
				"cdg" => 512,
				"nombre" => "ver_detalles_rol_proveedor",
				"descripcion" => "Ver detalles de Roles Proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 59,
				"cdg" => 513,
				"nombre" => "ver_listados_rol_proveedor",
				"descripcion" => "Ver listado de Roles Proveedores",
				"permiso_proveedor" => 0,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 60,
				"cdg" => 514,
				"nombre" => "ver_listados_usuarios_proveedor",
				"descripcion" => "Ver listado de Usuarios Proveedor",
				"permiso_proveedor" => 0,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 61,
				"cdg" => 212,
				"nombre" => "crear_marca",
				"descripcion" => "Creación de Marca",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 62,
				"cdg" => 213,
				"nombre" => "editar_marca",
				"descripcion" => "Editar de Marca",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 63,
				"cdg" => 214,
				"nombre" => "aprobar_marca",
				"descripcion" => "Aprobar Marca",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 64,
				"cdg" => 215,
				"nombre" => "rechazar_marca",
				"descripcion" => "Rechazar Marca",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 65,
				"cdg" => 216,
				"nombre" => "ver_detalle_marca",
				"descripcion" => "ver detalles Marca",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 66,
				"cdg" => 217,
				"nombre" => "ver_listados_marca",
				"descripcion" => "Ver listado Marca",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 67,
				"cdg" => 0,
				"nombre" => "ver_dashboar_resumen",
				"descripcion" => "Ver dashboard Resumen",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 68,
				"cdg" => 408,
				"nombre" => "ver_listado_plantillas_disponibles",
				"descripcion" => "Ver listado de plantillas disponibles",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 69,
				"cdg" => 409,
				"nombre" => "ver_plantilla_pdf",
				"descripcion" => "Ver diseño plantilla faldon",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 70,
				"cdg" => 410,
				"nombre" => "desactivar_plantilla",
				"descripcion" => "Desactivar plantilla Faldon",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 71,
				"cdg" => 411,
				"nombre" => "ver_detalles_platilla_faldon",
				"descripcion" => "Ver detalles plantilla faldon",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 72,
				"cdg" => 412,
				"nombre" => "ver_listado_faldones_express",
				"descripcion" => "Ver listado de faldones Express",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 73,
				"cdg" => 413,
				"nombre" => "crear_faldones_express",
				"descripcion" => "Crear faldones Express",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 74,
				"cdg" => 414,
				"nombre" => "editar_faldon_express",
				"descripcion" => "Editar faldones Express",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 75,
				"cdg" => 415,
				"nombre" => "descargar_pdf_faldon_express",
				"descripcion" => "Descargar faldon express pdf",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 76,
				"cdg" => 416,
				"nombre" => "ver_detalles_faldon_express",
				"descripcion" => "Ver detalles faldon Express",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 77,
				"cdg" => 417,
				"nombre" => "eliminar_faldon_express",
				"descripcion" => "Eliminar faldon Express",
				"permiso_proveedor" => 0,
				"id_modulo" => 4,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 78,
				"cdg" => 515,
				"nombre" => "ver_campanas_menu_proveedor",
				"descripcion" => "Ver Campaña menu Proveedor",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 79,
				"cdg" => 218,
				"nombre" => "eliminar_marca",
				"descripcion" => "Eliminar Marca",
				"permiso_proveedor" => 0,
				"id_modulo" => 1,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 80,
				"cdg" => 700,
				"nombre" => "ver_mantencion",
				"descripcion" => "Ver listado de Manteciones",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 81,
				"cdg" => 701,
				"nombre" => "crear_mantencion",
				"descripcion" => "Crear Mantención",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 82,
				"cdg" => 702,
				"nombre" => "editar_mantencion",
				"descripcion" => "Editar Mantención",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 83,
				"cdg" => 703,
				"nombre" => "eliminar_mantencion",
				"descripcion" => "Eliminar Mantención",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 84,
				"cdg" => 704,
				"nombre" => "aprobar_mantencion",
				"descripcion" => "Aprobar Mantención",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 85,
				"cdg" => 705,
				"nombre" => "rechazar_mantencion",
				"descripcion" => "Rechazar Mantención",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 86,
				"cdg" => 706,
				"nombre" => "ver_detalle_mantencion",
				"descripcion" => "Ver Detalle Mantención",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 87,
				"cdg" => 800,
				"nombre" => "ver_campaña_interna",
				"descripcion" => "Ver Campaña Interna",
				"permiso_proveedor" => 0,
				"id_modulo" => 8,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 88,
				"cdg" => 801,
				"nombre" => "crear_campaña_interna",
				"descripcion" => "Crear Campaña Interna",
				"permiso_proveedor" => 0,
				"id_modulo" => 8,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 89,
				"cdg" => 802,
				"nombre" => "editar_campaña_interna",
				"descripcion" => "Editar Campaña Interna",
				"permiso_proveedor" => 0,
				"id_modulo" => 8,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 90,
				"cdg" => 803,
				"nombre" => "eliminar_campaña_interna",
				"descripcion" => "Eliminar Campaña Interna",
				"permiso_proveedor" => 0,
				"id_modulo" => 8,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 91,
				"cdg" => 804,
				"nombre" => "gestionar_campaña_interna",
				"descripcion" => "Gestionar",
				"permiso_proveedor" => 0,
				"id_modulo" => 8,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 92,
				"cdg" => 805,
				"nombre" => "aprobar_campaña_interna",
				"descripcion" => "Aprobar",
				"permiso_proveedor" => 0,
				"id_modulo" => 8,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 93,
				"cdg" => 806,
				"nombre" => "rechazar_campaña_interna",
				"descripcion" => "Rechazar",
				"permiso_proveedor" => 0,
				"id_modulo" => 8,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 94,
				"cdg" => 807,
				"nombre" => "ver_detalle_campaña_interna",
				"descripcion" => "Ver Detalle Campaña Interna",
				"permiso_proveedor" => 0,
				"id_modulo" => 8,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 95,
				"cdg" => 900,
				"nombre" => "crear_campana",
				"descripcion" => "Crear las campañas de los promotoras",
				"permiso_proveedor" => 0,
				"id_modulo" => 9,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 96,
				"cdg" => 901,
				"nombre" => "editar_campana",
				"descripcion" => "Editar las campañas de los promotoras",
				"permiso_proveedor" => 0,
				"id_modulo" => 9,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 97,
				"cdg" => 902,
				"nombre" => "gestionar_campana",
				"descripcion" => "Gestiona las campañas de los promotoras",
				"permiso_proveedor" => 0,
				"id_modulo" => 9,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 98,
				"cdg" => 903,
				"nombre" => "implementar_campana",
				"descripcion" => "Implementar las campañas de los promotoras",
				"permiso_proveedor" => 0,
				"id_modulo" => 9,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 99,
				"cdg" => 904,
				"nombre" => "reportar_campana",
				"descripcion" => "Reportar las campañas de los promotoras",
				"permiso_proveedor" => 0,
				"id_modulo" => 9,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 100,
				"cdg" => 905,
				"nombre" => "eliminar_campana",
				"descripcion" => "Eliminar las campañas de los promotoras",
				"permiso_proveedor" => 0,
				"id_modulo" => 9,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 101,
				"cdg" => 906,
				"nombre" => "ver_campana",
				"descripcion" => "Ver las campañas de los promotoras",
				"permiso_proveedor" => 0,
				"id_modulo" => 9,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 102,
				"cdg" => 907,
				"nombre" => "subir_campana_proveedor",
				"descripcion" => "Subir la campanas de promotoras",
				"permiso_proveedor" => 1,
				"id_modulo" => 9,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 103,
				"cdg" => 1001,
				"nombre" => "ver_incidencias",
				"descripcion" => "Ver listado de incidencias",
				"permiso_proveedor" => 0,
				"id_modulo" => 10,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 104,
				"cdg" => 1002,
				"nombre" => "crear_incidencias",
				"descripcion" => "crear incidencias de campañas",
				"permiso_proveedor" => 0,
				"id_modulo" => 10,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 105,
				"cdg" => 1003,
				"nombre" => "editar_incidencias",
				"descripcion" => "editar incidencias de campañas",
				"permiso_proveedor" => 0,
				"id_modulo" => 10,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 106,
				"cdg" => 1004,
				"nombre" => "eliminar_incidencias",
				"descripcion" => "eliminar incidencias de campañas",
				"permiso_proveedor" => 0,
				"id_modulo" => 10,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 107,
				"cdg" => 516,
				"nombre" => "ver_incidencias_proveedor",
				"descripcion" => "ver inicidencias de campañas de su provvedor",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 108,
				"cdg" => 517,
				"nombre" => "ver_detalles_incidencias_proveedor",
				"descripcion" => "ver deatlles de incidencias capñas de su provvedor",
				"permiso_proveedor" => 1,
				"id_modulo" => 5,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => 0,
				"created_at" => "2021-04-21 23:36:31",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 109,
				"cdg" => 1005,
				"nombre" => "ver detalles incidencias ",
				"descripcion" => "muestra detalles incidencias de campañas",
				"permiso_proveedor" => 0,
				"id_modulo" => 10,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 110,
				"cdg" => 707,
				"nombre" => "ver_mantencion_subidas",
				"descripcion" => "ver lista de mantenciones subidas",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 111,
				"cdg" => 708,
				"nombre" => "ver_mantencion_liberadas",
				"descripcion" => "ver lista de mantenciones liberadas",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 112,
				"cdg" => 709,
				"nombre" => "ver_mantencion_devueltas",
				"descripcion" => "ver lista de mantenciones devueltas",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 113,
				"cdg" => 710,
				"nombre" => "ver_mantencion_aprobadas",
				"descripcion" => "ver lista de mantenciones aprobadas",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 114,
				"cdg" => 711,
				"nombre" => "ver_mantencion_rechazadas",
				"descripcion" => "ver lista de mantenciones rechazadas",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 115,
				"cdg" => 712,
				"nombre" => "ver_mantencion_finalizadas",
				"descripcion" => "ver lista de mantenciones terminadas",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 116,
				"cdg" => 713,
				"nombre" => "gestionar_mantencion",
				"descripcion" => "Gestionar mantencion",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 117,
				"cdg" => 714,
				"nombre" => "revisar_mantencion",
				"descripcion" => "Revizar mantencion",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			],
			[
				"id" => 118,
				"cdg" => 715,
				"nombre" => "finalizar_mantencion",
				"descripcion" => "Finalizar mantencion",
				"permiso_proveedor" => 0,
				"id_modulo" => 7,
				"id_usuario_crear" => 1,
				"id_usuario_modifica" => null,
				"created_at" => "2021-07-08 11:54:23",
				"updated_at" => null,
				"deleted_at" => null
			]
		];
		DB::table('permisos')->insert($permisos);
    }
}
